# This is a basic workflow to help you get started with Actions 

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      CHECKMARX_BASE_URL: "http://kk.com"
      LGV_KK: "{{ secrets.LGV_GH_API_TOKEN }}"
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world $Greeting $CHECKMARX_BASE_URL !

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          pwd
          ls -l
          env | grep CHECKMARX_BASE_URL
          #KKENV=<(env)
          env | grep LGV_KK

      # Run a cxFlow container
      - name: Run a cxFlow container
        run: |
          docker pull checkmarx/cx-flow
          docker run -v $(pwd)/application_LGV.yml:/app/application_LGV.yml -v $(pwd):/app/src checkmarx/cx-flow \
               --spring.config.location=/app/application_LGV.yml --spring.profiles.active=sast \
               --scan \
               --cx-project=KAKA --app=KAKA_APP --f=/app/src \
               --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.head_ref }} --merge-id=${{ github.event.number }} \
               --cx-flow.filterSeverity --cx-flow.filterCategory \
               --cx-flow.thresholds.high=0 --cx-flow.thresholds.medium=1 \
               --github.token=${{ secrets.LGV_GH_API_TOKEN }}
               
          # --github.url=http://jeje.com  --github.apiurl=http://jeje.com  --github.api-url=http://je-je.com \
               
          #docker run -v $(pwd)/application_LGV.yml:/app/application_LGV.yml checkmarx/cx-flow --spring.config.location=/app/application_LGV.yml --spring.profiles.active=sast --scan --cx-project=KAKA --app=KAKA_APP --f=. 
          #docker run checkmarx/cx-flow --spring.profiles.active=sast --scan --cx-project=KAKA --app=KAKA_APP --f=. 
